FACEBOOK_APP_ID : "995337833886860"
FACEBOOK_APP_SECRET : "7c20150b2f71c797a8f116f57788380d"

TWITTER_APP_ID : "bN0DY00w8bVn5YLLkhjxKjfR7"
TWITTER_APP_SECRET : "slJfj09bCeecQLdFDM9yFqq87jsw79OVknblBH6iZseNTvGsHJ"

GOOGLE_OAUTH2_APP_ID : "739380827443-ftp2l9knn6op71hvvvargp0rtpdl9nse.apps.googleusercontent.com"
GOOGLE_OAUTH2_APP_SECRET : "Qd1NnP4az-wXX-ifQhGCxTTS"