# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e9e5be42a9ebb097b164d5f3cd0549f1ea61eb96523ba611e127c272623de0e286244003b3b67407c58296c44db48ff4e2fc9b6d23db3360fcdd89a2aadd3dd

test:
  secret_key_base: bf2fc096bcec04d5565171eec2bc19bdaf37d917c9fc1bd2a8af7fa4a2f157c57a1b866e7f8d17a084f4cf007aa8582658d522106f08089c7b0c4841aab28db2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
